with base as (
  select
    id::text as work_id,
    title::text,
    display_name::text,
    publication_year::int,
    publication_date::timestamp,
    language::text,
    type::text,
    type_crossref::text,
    countries_distinct_count::int,
    institutions_distinct_count::int,
    fwci::int,
    has_fulltext::boolean,
    fulltext_origin::text,
    cited_by_count::int,
    is_retracted::boolean,
    is_paratext::boolean,
    locations_count::int,
    referenced_works_count::int,
    cited_by_api_url::text,
    updated_date::timestamp,
    created_date::timestamp,
    doi::text,
    mag::text,
    openalex::text,
    pmcid::text,
    pmid::text,
    
    {{ adapter.quote("primary_location.is_accepted") }}::boolean as primary_location_is_accepted,
    {{ adapter.quote("primary_location.is_oa") }}::boolean as primary_location_is_oa,
    {{ adapter.quote("primary_location.is_published") }}::boolean as primary_location_is_published,
    {{ adapter.quote("primary_location.landing_page_url") }}::text as primary_location_landing_page_url,
    {{ adapter.quote("primary_location.license") }}::text as primary_location_license,
    {{ adapter.quote("primary_location.license_id") }}::text as primary_location_license_id,
    {{ adapter.quote("primary_location.pdf_url") }}::text as primary_location_pdf_url,
    {{ adapter.quote("primary_location.version") }}::text as primary_location_version,
    {{ adapter.quote("primary_location.source.id") }}::text primary_location_source_id,
    {{ adapter.quote("primary_location.source.type") }}::text  primary_location_source_type,
    {{ adapter.quote("primary_location.source.display_name") }}::text primary_location_source_display_name,
    {{ adapter.quote("primary_location.source.host_organization") }}::text primary_location_source_host_organization,
    {{ adapter.quote("primary_location.source.host_organization_name") }}::text primary_location_source_host_organization_name,
    {{ adapter.quote("primary_location.source.is_core") }}::boolean primary_location_source_is_core,
    {{ adapter.quote("primary_location.source.is_in_doaj") }}::boolean primary_location_source_is_in_doaj,
    {{ adapter.quote("primary_location.source.is_indexed_in_scopus") }}::boolean primary_location_source_is_indexed_in_scopus,
    {{ adapter.quote("primary_location.source.is_oa") }}::boolean primary_location_source_is_oa,
    {{ adapter.quote("primary_location.source.issn_l") }}::text primary_location_source_issn_l,
    
    any_repository_has_fulltext::boolean,
    is_oa::boolean,
    oa_status::text,
    oa_url::text,
    
    {{ adapter.quote("apc_list.currency") }} as apc_list_currency,
    {{ adapter.quote("apc_list.value") }} as apc_list_value,
    {{ adapter.quote("apc_list.value_usd") }} as apc_list_value_usd,
    {{ adapter.quote("apc_paid.currency") }} as apc_paid_currency,
    {{ adapter.quote("apc_paid.value") }} as apc_paid_value,
    {{ adapter.quote("apc_paid.value_usd") }} as apc_paid_value_usd,
    {{ adapter.quote("citation_normalized_percentile.is_in_top_10_percent") }} as citation_normalized_percentile_is_in_top_10_percent,
    {{ adapter.quote("citation_normalized_percentile.is_in_top_1_percent") }} as citation_normalized_percentile_is_in_top_1_percent,
    {{ adapter.quote("citation_normalized_percentile.value") }} as citation_normalized_percentile_value,
    {{ adapter.quote("cited_by_percentile_year.max") }} as cited_by_percentile_year_max,
    {{ adapter.quote("cited_by_percentile_year.min") }} as cited_by_percentile_year_min,
    
    {{ adapter.quote("biblio.first_page") }} as biblio_first_page,
    {{ adapter.quote("biblio.issue") }} as biblio_issue,
    {{ adapter.quote("biblio.last_page") }} as biblio_last_page,
    {{ adapter.quote("biblio.volume") }} as biblio_volume,
    
    {{ adapter.quote("primary_topic.display_name") }} as topic_display_name,
    {{ adapter.quote("primary_topic.id") }} as topic_id,
    {{ adapter.quote("primary_topic.score") }} as primary_topic_score,
    {{ adapter.quote("primary_topic.domain.display_name") }} as topic_domain_display_name,
    {{ adapter.quote("primary_topic.domain.id") }} as topic_domain_id,
    {{ adapter.quote("primary_topic.field.display_name") }} as topic_field_display_name,
    {{ adapter.quote("primary_topic.field.id") }} as topic_field_id,
    {{ adapter.quote("primary_topic.subfield.display_name") }} as topic_subfield_display_name,
    {{ adapter.quote("primary_topic.subfield.id") }} as topic_subfield_id,
    
    {{ adapter.quote("best_oa_location.is_accepted") }}::boolean as best_oa_location_is_accepted,
    {{ adapter.quote("best_oa_location.is_oa") }}::boolean as best_oa_location_is_oa,
    {{ adapter.quote("best_oa_location.is_published") }}::boolean as best_oa_location_is_published,
    {{ adapter.quote("best_oa_location.landing_page_url") }}::text as best_oa_location_landing_page_url,
    {{ adapter.quote("best_oa_location.license") }}::text as best_oa_location_license,
    {{ adapter.quote("best_oa_location.license_id") }}::text as best_oa_location_license_id,
    {{ adapter.quote("best_oa_location.pdf_url") }}::text as best_oa_location_pdf_url,
    {{ adapter.quote("best_oa_location.version") }}::text as best_oa_location_version,
    --{{ adapter.quote("best_oa_location.source") }}::text as best_oa_location_source,
    {{ adapter.quote("best_oa_location.source.id") }}::text as best_oa_location_source_id,
    {{ adapter.quote("best_oa_location.source.display_name") }}::text as best_oa_location_source_display_name,
    {{ adapter.quote("best_oa_location.source.host_organization") }}::text as best_oa_location_source_host_organization,
    {{ adapter.quote("best_oa_location.source.host_organization_name") }}::text as best_oa_location_source_host_organization_name,
    {{ adapter.quote("best_oa_location.source.is_core") }}::text as best_oa_location_source_is_core,
    {{ adapter.quote("best_oa_location.source.is_in_doaj") }}::boolean as best_oa_location_source_is_in_doaj,
    {{ adapter.quote("best_oa_location.source.is_indexed_in_scopus") }}::boolean as best_oa_location_source_is_indexed_in_scopus,
    {{ adapter.quote("best_oa_location.source.is_oa") }}::boolean as best_oa_location_source_is_oa,
    {{ adapter.quote("best_oa_location.source.issn_l") }}::text as best_oa_location_source_issn_l,
    {{ adapter.quote("best_oa_location.source.type") }}::text as best_oa_location_source_type,
    load_datetime::timestamp
  from {{ source('openalex', 'work') }}
)

select * from base