version: 2

sources:
  - name: oai
    description: 'oai'
    schema: ldg_oai
    tables:
      - name: sets
      - name: records
        columns:
          - name: record_id
          - name: col_id
          - name: title
          - name: date_issued
          - name: extract_datetime
          - name: _context 
          - name: _load_datetime
      - name: map_record_creator
      - name: map_record_description
      - name: map_record_identifier
      - name: map_record_language
      - name: map_record_publisher
      - name: map_record_relation
      - name: map_record_right
      - name: map_record_set
      - name: map_record_subject
      - name: map_record_type
      - name: record_by_set
        columns:
          - name: record_id
          - name: handle
          - name: col_id
          - name: title
          - name: date_issued
          - name: type_openaire
          - name: type_snrd
          - name: version
          - name: access_right
          - name: license_condition
          - name: _load_datetime
      - name: record_creator
        columns:
          - name: handle
          - name: creator
          - name: _load_datetime
      - name: record_language
        columns:
          - name: handle
          - name: language_iso
          - name: _load_datetime
      - name: record_publisher
        columns:
          - name: handle
          - name: publisher
          - name: _load_datetime
      - name: record_relation
        columns:
          - name: handle
          - name: relation
          - name: _load_datetime
      - name: record_subject
        columns:
          - name: handle
          - name: relation
          - name: _load_datetime
