version: 2

sources:
  - name: dspace7
    description: 'DSpace 7 database'
    schema: public
    tables:
      - name: collection
      - name: collection2item
      - name: community
      - name: community2collection
      - name: community2community
      - name: dspaceobject
      - name: item
      - name: metadatafieldregistry
      - name: metadataschemaregistry
      - name: metadatavalue
