{{ config(materialized='table') }}

WITH ir_base AS (
    SELECT
        item_hk,
        item_id,
        source_label,
        institution_ror,
        dc_identifier_uri,
        dc_identifier_uri_raw,
        date_issued,
        date_accessioned,
        title,
        subtitle,
        type,
        description,
        subject,
        subtype,
        author,
        author_count,
        issn,
        isbn,
        has_doi,
        has_handle,
        doi_count,
        handle_count,
        doi,
        handle,
        owningcollection_hk,
        owning_collection_title,
        owning_community_hk,
        owning_community_id,
        owning_community_title,
        owning_root_community_hk,
        owning_root_community_id,
        owning_root_community_title,
        owning_community_path_ids,
        owning_community_path_titles,
        in_archive,
        withdrawn,
        discoverable
    FROM {{ ref('fct_unlp_ir_item_publication') }}
    WHERE discoverable = TRUE
      AND in_archive = TRUE
      AND withdrawn = FALSE
),

openalex_enrichment AS (
    SELECT
        match.item_hk,
        match.doi_normalized AS match_doi,
        oa.work_hk AS openalex_work_hk,
        oa.work_id AS openalex_work_id,
        oa.publication_date AS openalex_publication_date,
        oa.publication_year AS openalex_publication_year,
        oa.type AS openalex_type,
        oa.title AS openalex_title,
        oa.institution_ror AS openalex_institution_ror,
        oa.unlp_first_extract_datetime AS openalex_first_extract_datetime,
        oa.unlp_last_extract_datetime AS openalex_last_extract_datetime,
        oa.is_oa AS openalex_is_oa,
        oa.oa_status AS openalex_oa_status,
        oa.oa_url AS openalex_oa_url,
        oa.has_fulltext AS openalex_has_fulltext,
        oa.fulltext_origin AS openalex_fulltext_origin,
        oa.cited_by_count AS openalex_cited_by_count,
        oa.fwci AS openalex_fwci
    FROM {{ ref('brg_unlp_publication_doi') }} AS match
    INNER JOIN {{ ref('fct_unlp_openalex_work_publication') }} AS oa
        ON oa.work_hk = match.work_hk
    WHERE match.is_unique_match
),

unique_originalid_match AS (
    SELECT
        item_hk,
        original_id AS openaire_original_id,
        researchproduct_hk,
        researchproduct_id
    FROM {{ ref('brg_unlp_publication_originalid') }}
    WHERE is_unique_match
),

openaire_enrichment AS (
    SELECT
        match.item_hk,
        match.openaire_original_id,
        match.researchproduct_hk AS openaire_researchproduct_hk,
        match.researchproduct_id AS openaire_researchproduct_id,
        publication.unlp_first_extract_datetime AS openaire_first_extract_datetime,
        publication.unlp_last_extract_datetime AS openaire_last_extract_datetime,
        publication.organization_ror AS openaire_organization_ror,
        publication.publication_date AS openaire_publication_date,
        publication.type AS openaire_type,
        publication.main_title AS openaire_title,
        publication.publisher AS openaire_publisher,
        publication.best_access_right AS openaire_access_right,
        publication.best_access_right_uri AS openaire_access_right_uri,
        publication.is_green AS openaire_is_green,
        publication.is_in_diamond_journal AS openaire_is_in_diamond_journal,
        publication.downloads AS openaire_downloads,
        publication.views AS openaire_views,
        publication.citation_class AS openaire_citation_class,
        publication.citation_count AS openaire_citation_count,
        publication.impulse AS openaire_impulse,
        publication.impulse_class AS openaire_impulse_class,
        publication.influence AS openaire_influence,
        publication.influence_class AS openaire_influence_class,
        publication.popularity AS openaire_popularity,
        publication.popularity_class AS openaire_popularity_class,
        publication.has_arxiv AS openaire_has_arxiv,
        publication.has_single_arxiv AS openaire_has_single_arxiv,
        publication.arxiv_count AS openaire_arxiv_count,
        publication.has_doi AS openaire_has_doi,
        publication.has_single_doi AS openaire_has_single_doi,
        publication.doi_count AS openaire_doi_count,
        publication.has_handle AS openaire_has_handle,
        publication.has_single_handle AS openaire_has_single_handle,
        publication.handle_count AS openaire_handle_count,
        publication.has_mag AS openaire_has_mag,
        publication.has_single_mag AS openaire_has_single_mag,
        publication.mag_count AS openaire_mag_count,
        publication.has_pmb AS openaire_has_pmb,
        publication.has_single_pmb AS openaire_has_single_pmb,
        publication.pmb_count AS openaire_pmb_count,
        publication.has_pmc AS openaire_has_pmc,
        publication.has_single_pmc AS openaire_has_single_pmc,
        publication.pmc_count AS openaire_pmc_count,
        publication.has_pmid AS openaire_has_pmid,
        publication.has_single_pmid AS openaire_has_single_pmid,
        publication.pmid_count AS openaire_pmid_count,
        publication.has_sdg AS openaire_has_sdg,
        publication.sdg_count AS openaire_sdg_count,
        publication.sdg_values AS openaire_sdg_values
    FROM unique_originalid_match AS match
    INNER JOIN {{ ref('fct_unlp_openaire_researchproduct') }} AS publication
        USING (researchproduct_hk)
),

final AS (
    SELECT
        ir.item_hk AS publication_hk,
        ir.item_hk,
        ir.item_id,
        'ir'::text AS source_system,
        ir.source_label,
        ir.institution_ror,
        ir.dc_identifier_uri AS institutional_uri,
        ir.dc_identifier_uri_raw,
        ir.date_issued AS publication_date,
        EXTRACT(YEAR FROM ir.date_issued)::int AS publication_year,
        ir.date_accessioned,
        ir.title,
        ir.subtitle,
        ir.type AS publication_type,
        ir.description,
        ir.subject,
        ir.subtype,
        ir.author,
        ir.author_count,
        ir.issn,
        ir.isbn,
        ir.has_doi,
        ir.doi_count,
        ir.doi,
        ir.has_handle,
        ir.handle_count,
        ir.handle,
        ir.owningcollection_hk,
        ir.owning_collection_title,
        ir.owning_community_hk,
        ir.owning_community_id,
        ir.owning_community_title,
        ir.owning_root_community_hk,
        ir.owning_root_community_id,
        ir.owning_root_community_title,
        ir.owning_community_path_ids,
        ir.owning_community_path_titles,
        ir.discoverable,
        ir.in_archive,
        ir.withdrawn,

        (oa.openalex_work_hk IS NOT NULL) AS matched_by_unique_doi,
        oa.match_doi,
        oa.openalex_work_hk,
        oa.openalex_work_id,
        oa.openalex_publication_date,
        oa.openalex_publication_year,
        oa.openalex_type,
        oa.openalex_title,
        oa.openalex_institution_ror,
        oa.openalex_first_extract_datetime,
        oa.openalex_last_extract_datetime,
        oa.openalex_is_oa,
        oa.openalex_oa_status,
        oa.openalex_oa_url,
        oa.openalex_has_fulltext,
        oa.openalex_fulltext_origin,
        oa.openalex_cited_by_count,
        oa.openalex_fwci,

        (openaire.openaire_researchproduct_hk IS NOT NULL) AS matched_by_unique_original_id,
        openaire.openaire_original_id,
        openaire.openaire_researchproduct_hk,
        openaire.openaire_researchproduct_id,
        openaire.openaire_first_extract_datetime,
        openaire.openaire_last_extract_datetime,
        openaire.openaire_organization_ror,
        openaire.openaire_publication_date,
        openaire.openaire_type,
        openaire.openaire_title,
        openaire.openaire_publisher,
        openaire.openaire_access_right,
        openaire.openaire_access_right_uri,
        openaire.openaire_is_green,
        openaire.openaire_is_in_diamond_journal,
        openaire.openaire_downloads,
        openaire.openaire_views,
        openaire.openaire_citation_class,
        openaire.openaire_citation_count,
        openaire.openaire_impulse,
        openaire.openaire_impulse_class,
        openaire.openaire_influence,
        openaire.openaire_influence_class,
        openaire.openaire_popularity,
        openaire.openaire_popularity_class,
        openaire.openaire_has_arxiv,
        openaire.openaire_has_single_arxiv,
        openaire.openaire_arxiv_count,
        openaire.openaire_has_doi,
        openaire.openaire_has_single_doi,
        openaire.openaire_doi_count,
        openaire.openaire_has_handle,
        openaire.openaire_has_single_handle,
        openaire.openaire_handle_count,
        openaire.openaire_has_mag,
        openaire.openaire_has_single_mag,
        openaire.openaire_mag_count,
        openaire.openaire_has_pmb,
        openaire.openaire_has_single_pmb,
        openaire.openaire_pmb_count,
        openaire.openaire_has_pmc,
        openaire.openaire_has_single_pmc,
        openaire.openaire_pmc_count,
        openaire.openaire_has_pmid,
        openaire.openaire_has_single_pmid,
        openaire.openaire_pmid_count,
        openaire.openaire_has_sdg,
        openaire.openaire_sdg_count,
        openaire.openaire_sdg_values
    FROM ir_base AS ir
    LEFT JOIN openalex_enrichment AS oa USING (item_hk)
    LEFT JOIN openaire_enrichment AS openaire USING (item_hk)
)

SELECT * FROM final
