version: 2

models:
  - name: dim_unlp_author
    description: >
      Vista combinada de autores institucionales con datos de OpenAlex y OpenAIRE, unificados por ORCID.
    columns:
      - name: openalex_author_id
        description: Identificador del autor en OpenAlex
        data_tests:
          - unique
          - not_null

      - name: orcid
        description: ORCID del autor, normalizado sin prefijo
        data_tests:
          - unique
          - not_null
