version: 2

sources:
  - name: oai
    description: 'oai'
    schema: ldg_oai
    tables:
      - name: sets
      - name: records
      - name: record_identifiers
      - name: record_languages
      - name: record_publishers
      - name: record_relations
      - name: record_rights
      - name: record_subjects
      - name: record_types
      - name: record_by_set
        columns:
          - name: record_id
          - name: handle
          - name: col_id
          - name: title
          - name: date_issued
          - name: type_openaire
          - name: type_snrd
          - name: version
          - name: access_right
          - name: license_condition
          - name: load_datetime
      - name: record_creator
        columns:
          - name: handle
          - name: creator
          - name: load_datetime
      - name: record_language
        columns:
          - name: handle
          - name: language_iso
          - name: load_datetime
      - name: record_publisher
        columns:
          - name: handle
          - name: publisher
          - name: load_datetime
      - name: record_relation
        columns:
          - name: handle
          - name: relation
          - name: load_datetime
      - name: record_subject
        columns:
          - name: handle
          - name: relation
          - name: load_datetime
