{% set work_relation = source('openalex', 'work') %}
{% if execute %}
  {% set work_col_names = adapter.get_columns_in_relation(work_relation) | map(attribute='name') | map('lower') | list %}
{% else %}
  {% set work_col_names = none %}
{% endif %}

with source as (
  select * from {{ work_relation }}
),
renamed as (
  select
    id::text as work_id,
    title::text,
    display_name::text,
    publication_year::int,
    publication_date::timestamp,
    language::text,
    type::text,
    type_crossref::text,
    countries_distinct_count::int,
    institutions_distinct_count::int,
    fwci::int,
    has_fulltext::boolean,
    fulltext_origin::text,
    cited_by_count::int,
    is_retracted::boolean,
    is_paratext::boolean,
    locations_count::int,
    referenced_works_count::int,
    cited_by_api_url::text,
    updated_date::timestamp,
    created_date::timestamp,
	    doi::text,
	    mag::text,
	    openalex::text,
		    {{ safe_cast(work_relation, 'pmcid', 'text', alias='pmcid', default_sql="'!UNKNOWN'", col_names=work_col_names, default_mode='ghost') }},
		    pmid::text,
		    {{ safe_cast(work_relation, 'primary_location.is_accepted', 'boolean', alias='primary_location_is_accepted', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.is_oa', 'boolean', alias='primary_location_is_oa', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.is_published', 'boolean', alias='primary_location_is_published', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.landing_page_url', 'text', alias='primary_location_landing_page_url', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.license', 'text', alias='primary_location_license', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.license_id', 'text', alias='primary_location_license_id', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.pdf_url', 'text', alias='primary_location_pdf_url', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.version', 'text', alias='primary_location_version', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.id', 'text', alias='primary_location_source_id', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.type', 'text', alias='primary_location_source_type', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.display_name', 'text', alias='primary_location_source_display_name', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.host_organization', 'text', alias='primary_location_source_host_organization', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.host_organization_name', 'text', alias='primary_location_source_host_organization_name', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.is_core', 'boolean', alias='primary_location_source_is_core', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.is_in_doaj', 'boolean', alias='primary_location_source_is_in_doaj', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.is_indexed_in_scopus', 'boolean', alias='primary_location_source_is_indexed_in_scopus', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.is_oa', 'boolean', alias='primary_location_source_is_oa', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_location.source.issn_l', 'text', alias='primary_location_source_issn_l', col_names=work_col_names, default_mode='ghost') }},
		    any_repository_has_fulltext::boolean,
		    is_oa::boolean,
		    oa_status::text,
		    oa_url::text,
		    {{ safe_cast(work_relation, 'apc_list.currency', 'text', alias='apc_list_currency', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'apc_list.value', 'double precision', alias='apc_list_value', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'apc_list.value_usd', 'double precision', alias='apc_list_value_usd', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'apc_paid.currency', 'text', alias='apc_paid_currency', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'apc_paid.value', 'double precision', alias='apc_paid_value', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'apc_paid.value_usd', 'double precision', alias='apc_paid_value_usd', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'citation_normalized_percentile.is_in_top_10_percent', 'boolean', alias='citation_normalized_percentile_is_in_top_10_percent', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'citation_normalized_percentile.is_in_top_1_percent', 'boolean', alias='citation_normalized_percentile_is_in_top_1_percent', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'citation_normalized_percentile.value', 'double precision', alias='citation_normalized_percentile_value', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'cited_by_percentile_year.max', 'int', alias='cited_by_percentile_year_max', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'cited_by_percentile_year.min', 'int', alias='cited_by_percentile_year_min', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'biblio.first_page', 'text', alias='biblio_first_page', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'biblio.issue', 'text', alias='biblio_issue', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'biblio.last_page', 'text', alias='biblio_last_page', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'biblio.volume', 'text', alias='biblio_volume', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_topic.display_name', 'text', alias='primarytopic_display_name', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_topic.id', 'text', alias='primarytopic_id', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_topic.score', 'double precision', alias='primarytopic_score', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_topic.domain.display_name', 'text', alias='primarytopic_domain_display_name', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_topic.domain.id', 'text', alias='primarytopic_domain_id', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_topic.field.display_name', 'text', alias='primarytopic_field_display_name', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_topic.field.id', 'text', alias='primarytopic_field_id', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_topic.subfield.display_name', 'text', alias='primarytopic_subfield_display_name', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'primary_topic.subfield.id', 'text', alias='primarytopic_subfield_id', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.is_accepted', 'boolean', alias='best_oa_location_is_accepted', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.is_oa', 'boolean', alias='best_oa_location_is_oa', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.is_published', 'boolean', alias='best_oa_location_is_published', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.landing_page_url', 'text', alias='best_oa_location_landing_page_url', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.license', 'text', alias='best_oa_location_license', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.license_id', 'text', alias='best_oa_location_license_id', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.pdf_url', 'text', alias='best_oa_location_pdf_url', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.version', 'text', alias='best_oa_location_version', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.id', 'text', alias='best_oa_location_source_id', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.display_name', 'text', alias='best_oa_location_source_display_name', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.host_organization', 'text', alias='best_oa_location_source_host_organization', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.host_organization_name', 'text', alias='best_oa_location_source_host_organization_name', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.is_core', 'text', alias='best_oa_location_source_is_core', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.is_in_doaj', 'boolean', alias='best_oa_location_source_is_in_doaj', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.is_indexed_in_scopus', 'boolean', alias='best_oa_location_source_is_indexed_in_scopus', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.is_oa', 'boolean', alias='best_oa_location_source_is_oa', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.issn_l', 'text', alias='best_oa_location_source_issn_l', col_names=work_col_names, default_mode='ghost') }},
		    {{ safe_cast(work_relation, 'best_oa_location.source.type', 'text', alias='best_oa_location_source_type', col_names=work_col_names, default_mode='ghost') }},
    _load_datetime::timestamp
  from source
),
ghost_record as (
  select
    '!UNKNOWN'::text as work_id,
    '!UNKNOWN'::text as title,
    '!UNKNOWN'::text as display_name,
    -1::int as publication_year,
    '1900-01-01'::timestamp as publication_date,
    '!UNKNOWN'::text as language,
    '!UNKNOWN'::text as type,
    '!UNKNOWN'::text as type_crossref,
    -1::int as countries_distinct_count,
    -1::int as institutions_distinct_count,
    -1::int as fwci,
    false as has_fulltext,
    '!UNKNOWN'::text as fulltext_origin,
    -1::int as cited_by_count,
    false as is_retracted,
    false as is_paratext,
    -1::int as locations_count,
    -1::int as referenced_works_count,
    '!UNKNOWN'::text as cited_by_api_url,
    '1900-01-01'::timestamp as updated_date,
    '1900-01-01'::timestamp as created_date,
    '!UNKNOWN'::text as doi,
    '!UNKNOWN'::text as mag,
    '!UNKNOWN'::text as openalex,
    '!UNKNOWN'::text as pmcid,
    '!UNKNOWN'::text as pmid,
    false as primary_location_is_accepted,
    false as primary_location_is_oa,
    false as primary_location_is_published,
    '!UNKNOWN'::text as primary_location_landing_page_url,
    '!UNKNOWN'::text as primary_location_license,
    '!UNKNOWN'::text as primary_location_license_id,
    '!UNKNOWN'::text as primary_location_pdf_url,
    '!UNKNOWN'::text as primary_location_version,
    '!UNKNOWN'::text as primary_location_source_id,
    '!UNKNOWN'::text as primary_location_source_type,
    '!UNKNOWN'::text as primary_location_source_display_name,
    '!UNKNOWN'::text as primary_location_source_host_organization,
    '!UNKNOWN'::text as primary_location_source_host_organization_name,
    false as primary_location_source_is_core,
    false as primary_location_source_is_in_doaj,
    false as primary_location_source_is_indexed_in_scopus,
    false as primary_location_source_is_oa,
    '!UNKNOWN'::text as primary_location_source_issn_l,
    false as any_repository_has_fulltext,
    false as is_oa,
    '!UNKNOWN'::text as oa_status,
    '!UNKNOWN'::text as oa_url,
    '!UNKNOWN' as apc_list_currency,
    -1 as apc_list_value,
    -1 as apc_list_value_usd,
    '!UNKNOWN' as apc_paid_currency,
    -1 as apc_paid_value,
    -1 as apc_paid_value_usd,
    false as citation_normalized_percentile_is_in_top_10_percent,
    false as citation_normalized_percentile_is_in_top_1_percent,
    -1 as citation_normalized_percentile_value,
    -1 as cited_by_percentile_year_max,
    -1 as cited_by_percentile_year_min,
    '!UNKNOWN' as biblio_first_page,
    '!UNKNOWN' as biblio_issue,
    '!UNKNOWN' as biblio_last_page,
    '!UNKNOWN' as biblio_volume,
    '!UNKNOWN' as primarytopic_display_name,
    '!UNKNOWN' as primarytopic_id,
    -1 as primarytopic_score,
    '!UNKNOWN' as primarytopic_domain_display_name,
    '!UNKNOWN' as primarytopic_domain_id,
    '!UNKNOWN' as primarytopic_field_display_name,
    '!UNKNOWN' as primarytopic_field_id,
    '!UNKNOWN' as primarytopic_subfield_display_name,
    '!UNKNOWN' as primarytopic_subfield_id,
    false as best_oa_location_is_accepted,
    false as best_oa_location_is_oa,
    false as best_oa_location_is_published,
    '!UNKNOWN'::text as best_oa_location_landing_page_url,
    '!UNKNOWN'::text as best_oa_location_license,
    '!UNKNOWN'::text as best_oa_location_license_id,
    '!UNKNOWN'::text as best_oa_location_pdf_url,
    '!UNKNOWN'::text as best_oa_location_version,
    '!UNKNOWN'::text as best_oa_location_source_id,
    '!UNKNOWN'::text as best_oa_location_source_display_name,
    '!UNKNOWN'::text as best_oa_location_source_host_organization,
    '!UNKNOWN'::text as best_oa_location_source_host_organization_name,
    '!UNKNOWN'::text as best_oa_location_source_is_core,
    false as best_oa_location_source_is_in_doaj,
    false as best_oa_location_source_is_indexed_in_scopus,
    false as best_oa_location_source_is_oa,
    '!UNKNOWN'::text as best_oa_location_source_issn_l,
    '!UNKNOWN'::text as best_oa_location_source_type,
    {{ dbt_date.today() }} as _load_datetime
)
select * from renamed
union all
select * from ghost_record
