version: 2

models:
  - name: sat_dspacedb5_item__extract
    description: >
      Satélite multi-activo de observaciones de extracción por item contextualizado por
      repositorio e institución.
    columns:
      - name: item_hk
        description: Hash key del item contextualizado por repositorio e institución.
      - name: extract_datetime
        description: Fecha/hora de la extracción observada.
