WITH base AS (
    SELECT 
        hub_work.work_hk,
        hub_work.work_id,
        sat_work.title,
        sat_work.display_name,
        sat_work.language,
        sat_work.type,
        sat_work.type_crossref,
        sat_work.fulltext_origin,
        sat_work.cited_by_api_url,
        sat_work.has_fulltext,
        sat_work.is_retracted,
        sat_work.is_paratext,
        sat_work.institutions_distinct_count,
        sat_work.fwci,
        sat_work.cited_by_count,
        sat_work.locations_count,
        sat_work.referenced_works_count,
        sat_work.countries_distinct_count,
        sat_work.publication_year,
        sat_work.publication_date,
        sat_work.oa_status,
        sat_work.oa_url,
        sat_work.any_repository_has_fulltext,
        sat_work.is_oa,
        sat_work.apc_list_currency,
        sat_work.apc_list_value,
        sat_work.apc_list_value_usd,
        sat_work.apc_paid_currency,
        sat_work.apc_paid_value,
        sat_work.apc_paid_value_usd,
        sat_work.citation_normalized_percentile_is_in_top_10_percent,
        sat_work.citation_normalized_percentile_is_in_top_1_percent,
        sat_work.citation_normalized_percentile_value,
        sat_work.cited_by_percentile_year_max,
        sat_work.cited_by_percentile_year_min,
        sat_work.biblio_first_page,
        sat_work.biblio_issue,
        sat_work.biblio_last_page,
        sat_work.biblio_volume
    FROM {{ref('hub_openalex_work')}} hub_work 
    INNER JOIN {{ref('sat_openalex_work')}} sat_work USING (work_hk)
)

SELECT * FROM base