version: 2

models:
  - name: fct_oai_record_publication
    config:
      materialized: table
    tests:
      - unique:
          column_name: record_hk
          config:
            store_failures: true
            schema: "dbt_oai_failures"
      - not_null:
          column_name: record_hk