version: 2

sources:
  - name: openaire
    description: 'OpenAIRE Research Graph'
    schema: ldg_openaire
    tables:
      - name: researchproduct_alternateidentifiers
      - name: researchproduct_authors
      - name: researchproduct_instances
      - name: researchproduct_originalid
      - name: researchproduct_organizations
      - name: researchproduct_pids
      - name: researchproduct_subjects
      - name: researchproduct_sources
      - name: researchproduct
      - name: organization
      