version: 2

sources:
  - name: dspace5
    description: 'DSpace 5 database'
    schema: ldg_dspace5
    tables:
      - name: bitstream
        columns:
          - name: bitstream_format_id
          - name: size_bytes
          - name: checksum
          - name: checksum_algorithm
          - name: internal_id
          - name: deleted
          - name: store_number
          - name: sequence_id
      - name: bundle2bitstream
        columns:
          - name: id
          - name: bundle_id
          - name: bitstream_id
          - name: bitstream_order
      - name: collection
        columns:
          - name: collection_id
            data_tests:
            - unique
          - name: submitter
          - name: admin
      - name: collection2item
        columns:
          - name: id
            data_tests:
            - unique
            - not_null
          - name: collection_id
            data_tests:
            - not_null
          - name: item_id
            data_tests:
            - not_null
      - name: community
        columns:
          - name: community_id
            data_tests:
              - not_null
          - name: admin
      - name: community2collection
        columns:
          - name: id
            data_tests:
            - not_null
          - name: collection_id 
            data_tests:
            - not_null
          - name: community_id
            data_tests:
            - not_null
      - name: community2community
        columns:
          - name: id 
            data_tests:
            - not_null
          - name: parent_comm_id 
            data_tests:
            - not_null
          - name: child_comm_id
            data_tests:
            - not_null
      - name: handle
        columns:
          - name: handle
          - name: handle_id
          - name: resource_type_id
          - name: resource_id
      - name: item
        columns:
          - name: item_id
          - name: in_archive
            data_tests:
              - not_null
          - name: withdrawn
            data_tests:
              - not_null
          - name: last_modified
            data_tests:
              - not_null
          - name: discoverable
            data_tests:
              - not_null
          - name: submitter_id
          - name: owning_collection
      - name: item2bundle
        columns:
          - name: id
            data_tests:
              - not_null
          - name: item_id
            data_tests:
              - not_null
          - name: bundle_id
            data_tests:
              - not_null
      - name: metadatafieldregistry
        columns:
          - name: metadata_field_id
            data_tests:
              - unique
              - not_null
          - name: metadata_schema_id
            data_tests:
              - not_null
          - name: element
            data_tests:
              - not_null
          - name: qualifier
          - name: scope_note
      - name: metadataschemaregistry
        columns:
          - name: metadata_schema_id
            data_tests:
              - unique
              - not_null
          - name: namespace
            data_tests:
              - unique
              - not_null
          - name: short_id
            data_tests:
              - unique
              - not_null
      - name: metadatavalue
        columns:
          - name: metadata_value_id
            data_tests:
            - not_null
          - name: resource_id
            data_tests:
            - not_null
          - name: resource_type_id
            data_tests:
            - not_null
          - name: metadata_field_id
            data_tests:
            - not_null
          - name: text_value
            data_tests:
            - not_null
          - name: text_lang
          - name: place
          - name: authority
          - name: confidence
          - name: dspace_object_id
            data_tests:
            - not_null
